#!/usr/bin/env python

import subprocess
import sys
import re
import inspect


class Paper(object):

    ##########################################################################
    # INTERNAL STUFF
    ##########################################################################

    def __init__(self, filenames):
        clean_fulltext = subprocess.check_output(["detex"] + filenames)
        fulltext = ''
        for filename in filenames:
            with open(filename) as f:
                fulltext += f.read() + '\n'

        flatten_paragraphs = lambda text: '\n'.join(
                        paragraph.replace('\n', ' ')
                        for paragraph in re.split("\n(\s*\n)+", text)
                        if paragraph.strip())
        self.fulltext = flatten_paragraphs(fulltext)
        self.clean_fulltext = flatten_paragraphs(clean_fulltext)

    def __run_all_with_prefix(self, prefix):
        for name in filter(lambda n: n.startswith(prefix), dir(self)):
            attribute = getattr(self, name)
            if inspect.ismethod(attribute):
                attribute()

    def run_all_checks(self):
        self.__run_all_with_prefix('check_')

    def run_all_tests(self):
        self.__run_all_with_prefix('test_')

    def _format_re_match(self, m, text):
        start_of_sentence = max(text.rfind('\n', 0, m.start()) + 1, 0)
        end_of_sentence = text.find('\n', m.end()), len(text)
        if end_of_sentence == -1:
            end_of_sentence = len(text)
        a_string = text[max(start_of_sentence, m.start() - 10):
                        min(end_of_sentence, m.end() + 10)]
        return a_string.split('\n', 1)[0]

    ##########################################################################
    # CHECKS
    ##########################################################################

    def check_exempli_gratia_without_comma(self):
        errors = 0
        for m in re.finditer(r'e\.g\.[^,]',
                             self.clean_fulltext,
                             re.MULTILINE):
            print "E.G. without comma:", self._format_re_match(m,
                                            self.clean_fulltext)
            errors += 1
        return errors

    def test__check_exempli_gratia_without_comma(self):
        self.clean_fulltext = "e.g. a pony \n e.g. what?, e.g., cool!"
        assert self.check_exempli_gratia_without_comma() == 2

    ##########################################################################

    def check_id_est_without_comma(self):
        errors = 0
        for m in re.finditer(r'i\.e\.[^,]',
                             self.clean_fulltext,
                             re.MULTILINE):
            print "I.E. without comma:", self._format_re_match(m,
                                            self.clean_fulltext)
            errors += 1
        return errors

    def test__check_id_est_without_comma(self):
        self.clean_fulltext = "i.e. a pony \n i.e. what?, i.e., cool!"
        assert self.check_id_est_without_comma() == 2

    ##########################################################################

    def check_quotes(self):
        errors = 0
        for m in re.finditer(r'"',
                             self.clean_fulltext,
                             re.MULTILINE):
            print '"hello" should be substituted with ``hello\'\':', \
                                self._format_re_match(m, self.clean_fulltext)
            errors += 1
        return errors

    def test__check_quotes(self):
        self.clean_fulltext = '"this is not ok" ``but this is\'\''
        assert self.check_quotes() == 2

    ##########################################################################

    def check_citing_with_unbreakeable_spaces(self):
        errors = 0
        for keyword in ["cite", "ref"]:
            for m in re.finditer(r'(^|\s)\\' + keyword + r'\s*{',
                                 self.clean_fulltext,
                                 re.MULTILINE):
                print 'use hello~\%s{ instead of hello \%s{:' % (keyword,
                                                                 keyword), \
                            self._format_re_match(m, self.clean_fulltext)
                errors += 1
        return errors

    def test__check_citing_with_unbreakeable_spaces(self):
        self.clean_fulltext = r'citing: wrong \cite{ciao} - right~\cite{ciao}'
        assert self.check_citing_with_unbreakeable_spaces() == 1
        self.clean_fulltext = r'refs done wrong \ref{ciao} - right~\ref{ciao}'
        assert self.check_citing_with_unbreakeable_spaces() == 1

    ##########################################################################

    def check_commas_in_numbers(self):
        errors = 0
        for m in re.finditer('(^|[^\w\-])\d{5}',
                             self.clean_fulltext,
                             re.MULTILINE):
            print 'Put commas in numbers over 10,000:', \
                                self._format_re_match(m, self.clean_fulltext)
            errors += 1
        for m in re.finditer('[^\d]\d,\d{3}[^,]',
                             self.clean_fulltext,
                             re.MULTILINE):
            print "Don't put commas in numbers under 10,000:", \
                                self._format_re_match(m, self.clean_fulltext)
            errors += 1
        return errors

    def test__check_commas_in_numbers(self):
        self.clean_fulltext = r'10000 cats eat 10,000 mice'
        assert self.check_commas_in_numbers() == 1
        self.clean_fulltext = r'9999 cats eat 9,999 mice'
        assert self.check_commas_in_numbers() == 1
        self.clean_fulltext = r'1000 cats eat 999,999 mice'
        assert self.check_commas_in_numbers() == 0
        self.clean_fulltext = r'project N10000, grant CNS-20000'
        assert self.check_commas_in_numbers() == 0

    ##########################################################################

    def check_commas_after_quotes(self):
        errors = 0
        for m in re.finditer("''\s*,",
                             self.clean_fulltext,
                             re.MULTILINE):
            print "Convert ``hello'', => ``hello,'' :", \
                                self._format_re_match(m, self.clean_fulltext)
            errors += 1
        return errors

    def test__check_commas_after_quotes(self):
        self.clean_fulltext = r"``flower'', should be ``flower,''"
        assert self.check_commas_after_quotes() == 1

    ##########################################################################

    def check_always_capitalize(self):
        errors = 0

        for reg in ["internet"]:
            for m in re.finditer(reg,
                                 self.clean_fulltext,
                                 re.MULTILINE):
                print "Always capitalize:", \
                            self._format_re_match(m, self.clean_fulltext)
                errors += 1
        return errors

    def test__check_always_capitalize(self):
        self.clean_fulltext = r"internet"
        assert self.check_always_capitalize() == 1

    ##########################################################################

    def check_comma_before_that(self):
        errors = 0
        for m in re.finditer(",\s+that",
                             self.clean_fulltext,
                             re.MULTILINE):
            print "Do not put a comma before 'that':", \
                                self._format_re_match(m, self.clean_fulltext)
            errors += 1
        return errors

    def test__check_comma_before_that(self):
        self.clean_fulltext = r"I like cats, that eat mice"
        assert self.check_comma_before_that() == 1
        self.clean_fulltext = r"I like cats that eat mice"
        assert self.check_comma_before_that() == 0

    ##########################################################################

    def check_comma_before_which(self):
        errors = 0
        for m in re.finditer("[^,\s]\s+which",
                             self.clean_fulltext,
                             re.MULTILINE):
            word_before_start = self.clean_fulltext.rfind(' ', 0, m.start())
            word_before = re.search("\w+", self.clean_fulltext[
                                                word_before_start + 1:
                                                m.start() + 1]).group()
            if word_before in ["in", "for", "of", "before", "after", "from",
                               "through"]:
                continue
            print "Put a comma before 'which':", \
                                self._format_re_match(m, self.clean_fulltext)
            errors += 1
        return errors

    def test__check_comma_before_which(self):
        self.clean_fulltext = r"I like that cat, which eat mice"
        assert self.check_comma_before_which() == 0
        self.clean_fulltext = r"I like that cat which eat mice"
        assert self.check_comma_before_which() == 1

    ##########################################################################
        
    def check_british_spelling(self):
        errors = 0
        british_spellings = {"acknowledgement": "acknowledgment", "afterwards": "afterward", "arse": "ass", "backwards": "backward", "besides": "beside", 
                             "cancelling": "canceling", "catalogue": "catalog", "centre": "center", "cheque": "check", "colour": "color", "dialogue": "dialog",
                             "favour": "favor", "flavour": "flavor", "forwards": "forward", "grey": "gray", "judgement": "judgment", "labour": "labor",
                             "lustre": "luster", "modelled": "modeled", "revelled": "raveled", "shovelled": "shoveled", "snivelled": "sniveled", 
                             "theatre": "theater", "towards": "toward", "travelling": "traveling", "yodelling": "yodeling"}
        for british, american in british_spellings.iteritems():
            for m in re.finditer("[^\w]+" + british + "[^\w]+", self.clean_fulltext):
                print "Don't spell like a bugger", american, "not", self._format_re_match(m, self.clean_fulltext)
                errors += 1
        return errors

    def test__check_british_spelling(self):
        self.clean_fulltext = r"Go to the (centre) of town to pick up the best flavour colour."
        assert self.check_british_spelling() == 3
        self.clean_fulltext = r"I am an American, therefore I am"
        assert self.check_british_spelling() == 0
        self.clean_fulltext = r"This cheque, right here, is unacceptable. I'll have to cheque with my manager."
        assert self.check_british_spelling() == 2
        self.clean_fulltext = r"It is hard to parse this sentence."
        assert self.check_british_spelling() == 0

    ##########################################################################

    def check_is_comprised_of(self):
        errors = 0
        for m in re.finditer("([^\w]+|^)is[\s]+comprised[\s]+of[^\w]+", self.clean_fulltext, flags=re.IGNORECASE):
            print "Don't use 'is comprised of'. Bugs book segment 75.", self._format_re_match(m, self.clean_fulltext)
            errors += 1
        return errors

    def test__check_is_comprised_of(self):
        self.clean_fulltext = r"Adam is comprised of a brain and a stomach."
        assert self.check_is_comprised_of() == 1
        self.clean_fulltext = r"Adam comprises a brain and a stomach."
        assert self.check_is_comprised_of() == 0
        self.clean_fulltext = r"You don't know what that is. Comprised. Of."
        assert self.check_is_comprised_of() == 0
        self.clean_fulltext = r"Is comprised of blah and bloop."
        assert self.check_is_comprised_of() == 1
        self.clean_fulltext = r"Adam is awesome. Is comprised of blah and bloop."
        assert self.check_is_comprised_of() == 1

if __name__ == '__main__':
    if sys.argv[1] == "test":
        Paper(sys.argv[2:]).run_all_tests()
    else:
        Paper(sys.argv[1:]).run_all_checks()
